/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package technical.interview.questions;

import org.junit.Test;

import com.saif.string.ReverseString;

import static org.junit.Assert.*;

public class StringManipulationTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void testReverseString() {
    	String str = "olleH";
    	System.out.println("Before reverse String: " + str);
    	String reverseStr = ReverseString.reverseString(str);
    	System.out.println("After reverse : " + reverseStr);
    }
}
